### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by ghost** [RandomGamingDev/EzCopenheimer#4]
make a better scanner this one kinda sucks nlg it doesent even have a rescanner or a db and its veeeeery slow use masscan or (atleast) non-blocking sockets

**Comment by RandomGamingDev** [comment]
The youtube video, my messages on the repo itself (one of which you literally commented under), and everything else literally say that it's an educational tool. Using masscan doesn't serve that purpose. Using non-blocking sockets would mean increasing the complexity, going completely against the idea of being able to look at each component and library to understand Copenheimer from the ground up.
For instance, I would've loved to be able to read the data for scanning from a Python file and then use a local Postgres database for storing the data, but that would've added extra unneeded complexity that would've deviated away from the original educational purpose.

**Comment by RandomGamingDev** [comment]
I've added further comments on the description and readme other than the already prevalent reminders that this is an educational tool in case you still plan on misinterpreting its use case.

**Comment by sandia-hd** [comment]
hi lol

**Comment by RandomGamingDev** [comment]
> hi lol

Hello?
